import { randomUUID } from 'node:crypto';
import { get, all, run, nowSQL } from '../db/index.js';
import { cleanText } from './markdown.js';

// ── §02c / §04 — SOURCE MATERIAL ─────────────────────────
//
// "The research board — the archival images, uniforms and found objects a
// designer pins to the wall before a garment exists."
//
// §04 is the reason this file exists at all rather than a prompt:
//
//   "If research boards are auto-generated by a model, they will produce
//    exactly the error corrected above — confident, wrong, and set in
//    beautiful type, which makes people believe it MORE. Typographic
//    authority is the danger, not the feature."
//
// The spec ranks three mitigations. This implements the one it calls "likely
// the product" — readers build their own — with the second layered on top,
// because they compose: every entry carries a visible source, so even a
// hand-made board shows its working.
//
// The first mitigation is the fallback: a book with no board simply gets its
// look plate and composition label. A missing board is a normal state, not a
// gap to be filled with something plausible.

export const MAX_ENTRIES = 6;         // §02c — "Six found images per book."
export const MAX_LINEAGE = 5;
export const RELATIONS = ['source', 'intermediary'];

export const CREDIT_ROLES = ['translator', 'cover_design', 'typeset', 'editor'];

/**
 * The board shown for a work.
 *
 * A reader sees their own board. Where they have none, they see the
 * canonical one if a curator has verified it — §04's "user boards can
 * accrete into the canonical board over time". They never see a stranger's
 * unverified board: an unverified board is one person's research, and
 * showing it to somebody else in this typography would lend it an authority
 * nobody granted it.
 */
export function boardFor(workId, userId) {
  const mine = userId
    ? get('SELECT * FROM source_boards WHERE work_id = ? AND user_id = ?',
          Number(workId), Number(userId))
    : null;

  const board = mine
    || get('SELECT * FROM source_boards WHERE work_id = ? AND canonical = 1 LIMIT 1', Number(workId));

  if (!board) return null;

  const entries = all(
    'SELECT * FROM board_entries WHERE board_id = ? ORDER BY ordinal', board.id
  );
  if (!entries.length && !board.set_year_from) return null;

  return { ...board, entries, mine: !!mine };
}

export const lineageFor = (boardId) =>
  all('SELECT * FROM lineage WHERE board_id = ? ORDER BY ordinal', boardId);

export function ensureBoard(workId, userId) {
  const existing = get('SELECT * FROM source_boards WHERE work_id = ? AND user_id = ?',
                       Number(workId), Number(userId));
  if (existing) return existing;

  const id = randomUUID();
  run('INSERT INTO source_boards (id, work_id, user_id) VALUES (?, ?, ?)',
      id, Number(workId), Number(userId));
  return get('SELECT * FROM source_boards WHERE id = ?', id);
}

/**
 * Replace a board's contents wholesale.
 *
 * Boards are small and edited as a single form, so a replace is both simpler
 * and safer than a diff — there is no path where half an edit lands.
 */
export function saveBoard(workId, userId, { entries = [], lineage = [], setFrom, setTo }) {
  const board = ensureBoard(workId, userId);

  const clean = entries
    .map((e) => ({
      label: cleanText(e.label, { max: 90 }),
      source: cleanText(e.source, { max: 120 }),
      year: e.year ? Number(e.year) : null
    }))
    // §04 mitigation two is not advisory: an entry without a source is not
    // saved, because an uncited line set in this type is the failure mode.
    .filter((e) => e.label && e.source)
    .slice(0, MAX_ENTRIES);

  const cleanLineage = lineage
    .map((l) => ({
      ancestor: cleanText(l.ancestor, { max: 90 }),
      relation: RELATIONS.includes(l.relation) ? l.relation : 'source',
      year: l.year ? Number(l.year) : null,
      source: cleanText(l.source, { max: 120 })
    }))
    .filter((l) => l.ancestor && l.source)
    .slice(0, MAX_LINEAGE);

  run('DELETE FROM board_entries WHERE board_id = ?', board.id);
  clean.forEach((e, i) =>
    run(`INSERT INTO board_entries (id, board_id, ordinal, label, source, year)
         VALUES (?, ?, ?, ?, ?, ?)`,
        randomUUID(), board.id, i + 1, e.label, e.source, e.year));

  run('DELETE FROM lineage WHERE board_id = ?', board.id);
  cleanLineage.forEach((l, i) =>
    run(`INSERT INTO lineage (id, board_id, ordinal, ancestor, relation, year, source)
         VALUES (?, ?, ?, ?, ?, ?, ?)`,
        randomUUID(), board.id, i + 1, l.ancestor, l.relation, l.year, l.source));

  const yearOf = (v) => {
    const n = Number(v);
    // A four-digit-ish year, and BCE as a negative. Anything else is not a
    // year and is dropped rather than stored as a plausible-looking number.
    return Number.isInteger(n) && n >= -4000 && n <= 2400 ? n : null;
  };

  run('UPDATE source_boards SET set_year_from = ?, set_year_to = ?, updated_at = ? WHERE id = ?',
      yearOf(setFrom), yearOf(setTo), nowSQL(), board.id);

  return { ok: true, entries: clean.length, lineage: cleanLineage.length };
}

// ── §02e band 2 — the author's life ──────────────────────
export const lifeOf = (personId) =>
  get('SELECT * FROM person_life WHERE person_id = ?', Number(personId)) || null;

export function saveLife(personId, userId, { born, died, source }) {
  const src = cleanText(source, { max: 120 });
  if (!src) return { ok: false, error: 'Say where the dates came from.' };

  const yearOf = (v) => {
    const n = Number(v);
    return Number.isInteger(n) && n >= -4000 && n <= 2400 ? n : null;
  };
  const b = yearOf(born);
  if (!b) return { ok: false, error: 'A birth year is needed for the band.' };

  run(
    `INSERT INTO person_life (person_id, born_year, died_year, source, added_by)
     VALUES (?, ?, ?, ?, ?)
     ON CONFLICT (person_id) DO UPDATE SET
       born_year = excluded.born_year, died_year = excluded.died_year,
       source = excluded.source, added_by = excluded.added_by`,
    Number(personId), b, yearOf(died), src, Number(userId)
  );
  return { ok: true };
}

// ── §02 back matter — credits ────────────────────────────
//
// The catalogue's own credits and the reader's additions, merged. Both carry
// a source, because "cover designer named" is only worth printing if the
// reader can see who says so.
const CATALOGUE_ROLES = {
  TRANSLATION: 'translator', TRANSLATOR: 'translator',
  COVER: 'cover_design', DESIGN: 'cover_design', ILLUSTRATION: 'cover_design',
  EDITOR: 'editor', INTRODUCTION: 'editor'
};

export const creditsFor = (editionId) => [
  ...all(
    `SELECT p.name, ec.role FROM edition_credits ec
       JOIN people p ON p.id = ec.person_id
      WHERE ec.edition_id = ?`,
    Number(editionId)
  ).map((c) => ({
    name: c.name,
    role: CATALOGUE_ROLES[String(c.role).toUpperCase()] || String(c.role).toLowerCase(),
    source: 'OPEN LIBRARY'
  })),
  ...all(
    'SELECT id, name, role, source FROM credit_additions WHERE edition_id = ? ORDER BY role, name',
    Number(editionId)
  )
];

export function addCredit(editionId, userId, { role, name, source }) {
  if (!CREDIT_ROLES.includes(role)) return { ok: false, error: 'Unknown role.' };

  const n = cleanText(name, { max: 90 });
  const src = cleanText(source, { max: 120 });
  if (!n || !src) return { ok: false, error: 'A name and a source, both.' };

  run(`INSERT INTO credit_additions (id, edition_id, role, name, source, added_by)
       VALUES (?, ?, ?, ?, ?, ?)`,
      randomUUID(), Number(editionId), role, n, src, Number(userId));
  return { ok: true };
}

export function removeCredit(id, userId) {
  run('DELETE FROM credit_additions WHERE id = ? AND added_by = ?', id, Number(userId));
  return { ok: true };
}
