// ── THE COLOUR SYSTEM, §01 ───────────────────────────────
//
// Twenty colours. Fixed, closed, not extensible by users, and not derived
// from anything at runtime — this file is the whole palette and there is no
// other source of a book colour anywhere in the product.
//
// The set is small on purpose. §01: a closed palette is what makes two
// seasons comparable, what keeps a colourway coherent without anyone art
// directing it, and roughly the resolution the evidence supports. Finer
// distinctions than these are past the research.
//
// Hue anchors follow the documented emotion→colour associations (red→anger,
// yellow→joy, black→sadness and fear, blue→calm, grey→sadness); lightness
// tracks valence and saturation tracks arousal. The names are ours. Nothing
// here references or cross-maps to any proprietary colour system, per §06.

/**
 * `valence` and `arousal` are stored as enums rather than numbers because
 * §01 wants the set re-tunable without touching anything already assigned:
 * they order the picker and they are the axis a future revision would move
 * a colour along, and neither use wants a false precision.
 */
export const VALENCE = ['−', '~', '+'];
export const AROUSAL = ['low', 'mid', 'high'];

export const PALETTE = Object.freeze([
  { id: 'dread',          emotion: 'Dread',          name: 'Pitch, Oxidised', hex: '#2A1416', valence: '−', arousal: 'high' },
  { id: 'anger',          emotion: 'Anger',          name: 'Flare',           hex: '#A81F27', valence: '−', arousal: 'high' },
  { id: 'anxiety',        emotion: 'Anxiety',        name: 'Acid, Unstable',  hex: '#A8B02A', valence: '−', arousal: 'high' },
  { id: 'grief',          emotion: 'Grief',          name: 'Slate, Deep',     hex: '#23262B', valence: '−', arousal: 'mid'  },
  { id: 'melancholy',     emotion: 'Melancholy',     name: 'Indigo, Washed',  hex: '#3A4159', valence: '−', arousal: 'low'  },
  { id: 'loneliness',     emotion: 'Loneliness',     name: 'Harbour Grey',    hex: '#7C8894', valence: '−', arousal: 'low'  },
  { id: 'boredom',        emotion: 'Boredom',        name: 'Flannel',         hex: '#8E8880', valence: '−', arousal: 'low'  },
  { id: 'desolation',     emotion: 'Desolation',     name: 'Salt',            hex: '#C3C6C4', valence: '−', arousal: 'low'  },
  { id: 'disorientation', emotion: 'Disorientation', name: 'Smoke Violet',    hex: '#5E5470', valence: '~', arousal: 'mid'  },
  { id: 'awe',            emotion: 'Awe',            name: 'Deep Field',      hex: '#101A2E', valence: '~', arousal: 'high' },
  { id: 'clarity',        emotion: 'Clarity',        name: 'Glass',           hex: '#DCE4E8', valence: '+', arousal: 'low'  },
  // v1.1 §7.6 — was "Being seen", the only phrase among nineteen nouns.
  { id: 'recognition',    emotion: 'Recognition',    name: 'Bone, Warm',      hex: '#E0D5C2', valence: '+', arousal: 'low'  },
  { id: 'calm',           emotion: 'Calm',           name: 'Still Water',     hex: '#6E93A8', valence: '+', arousal: 'low'  },
  { id: 'tenderness',     emotion: 'Tenderness',     name: 'Rose, Dusted',    hex: '#C99A97', valence: '+', arousal: 'low'  },
  { id: 'nostalgia',      emotion: 'Nostalgia',      name: 'Amber, Kept',     hex: '#B08A4E', valence: '+', arousal: 'low'  },
  { id: 'contentment',    emotion: 'Contentment',    name: 'Sage, Worn',      hex: '#7E9074', valence: '+', arousal: 'low'  },
  { id: 'wonder',         emotion: 'Wonder',         name: 'Night Violet',    hex: '#4B3E86', valence: '+', arousal: 'mid'  },
  { id: 'desire',         emotion: 'Desire',         name: 'Carmine, Soft',   hex: '#C2456B', valence: '+', arousal: 'high' },
  { id: 'delight',        emotion: 'Delight',        name: 'Brass',           hex: '#E8C34A', valence: '+', arousal: 'high' },
  { id: 'exhilaration',   emotion: 'Exhilaration',   name: 'Signal Orange',   hex: '#E2612B', valence: '+', arousal: 'high' }
]);

const BY_ID = new Map(PALETTE.map((c) => [c.id, c]));

// ── THE NAME GRAMMAR ─────────────────────────────────────
//
// A blended colour is not an anchor, so it cannot borrow an anchor's name
// outright — six books mixing toward the same slate would all be called
// "Slate, Deep" and the name would stop describing anything.
//
// Fixed grammar, two slots, no free text:
//
//   <base of the nearest anchor> , <modifier of the second component>
//
// "Slate, Kept" is grief nearest with nostalgia behind it. "Slate, Dusted"
// is the same grief with tenderness behind it instead. The name moves when
// the blend moves, and it moves in a way somebody can learn to read.
//
// Nothing here is generated by a model. The register is the one the anchors
// were written in, and every possible output is one of 20 × 20 strings.

const MODIFIER = Object.freeze({
  dread: 'Oxidised',      anger: 'Flared',        anxiety: 'Unstable',
  grief: 'Deep',          melancholy: 'Washed',   loneliness: 'Distant',
  boredom: 'Flat',        desolation: 'Salted',   disorientation: 'Smoked',
  awe: 'Vast',            clarity: 'Clear',       recognition: 'Warm',
  calm: 'Stilled',        tenderness: 'Dusted',   nostalgia: 'Kept',
  contentment: 'Worn',    wonder: 'Struck',       desire: 'Softened',
  delight: 'Bright',      exhilaration: 'Quick'
});

/** "Slate, Deep" → "Slate". "Harbour Grey" → "Harbour Grey". */
export const baseName = (name) => String(name || '').split(',')[0].trim();

/**
 * The name of a blend.
 *
 * The base is the HEAVIEST component's anchor; the modifier is the second's.
 *
 * It used to take the base from whichever anchor the blend landed nearest,
 * which collapsed: blends sit inside the hull of their components and drift
 * to the middle of the palette, where Smoke Violet is. The name disagreed
 * with the dominant component on 79% of cards, and a panel reading 73%
 * Melancholy sat above a name saying Smoke Violet.
 */
export function blendName(nearestId, secondId) {
  const near = colourOf(nearestId);
  if (!near) return null;
  const mod = MODIFIER[secondId];
  // A single-component colour is an anchor, and keeps the anchor's own name.
  if (!mod || secondId === nearestId) return near.name;
  return `${baseName(near.name)}, ${mod}`;
}

/** The entry, or null. Never throws: an unknown id is a data question. */
export const colourOf = (id) => BY_ID.get(String(id || '')) || null;

export const isColourId = (id) => BY_ID.has(String(id || ''));

/**
 * The anchor nearest a colour, perceptually.
 *
 * No longer used for naming — see `blendName` for why that collapsed — and
 * kept because it is the honest way to ask "which anchor is this closest
 * to", which the audit uses when reporting where a library sits.
 */
export function nearestAnchor(hex, oklabModule) {
  const { oklab, distance } = oklabModule;
  const target = oklab(hex);
  if (!target) return null;
  let best = null;
  for (const c of PALETTE) {
    const d = distance(target, oklab(c.hex));
    if (!best || d < best.d) best = { ...c, d };
  }
  return best;
}

/** Every id, for a prompt or a validator. */
export const IDS = PALETTE.map((c) => c.id);

/**
 * The picker order.
 *
 * By valence then arousal, so the twenty read as a range from the darkest
 * negative to the brightest positive rather than as a list somebody typed.
 * A reader scanning for "the one that fits" is scanning a gradient.
 */
export const ordered = () => [...PALETTE].sort((a, b) =>
  VALENCE.indexOf(a.valence) - VALENCE.indexOf(b.valence) ||
  AROUSAL.indexOf(a.arousal) - AROUSAL.indexOf(b.arousal) ||
  a.emotion.localeCompare(b.emotion));

// ── CONTRAST ─────────────────────────────────────────────
//
// §05 asks for a contrast check and names six swatches it expects to fail.
// All six do. So do nine more — measured, not guessed — and the failures are
// complementary: eight fall under 3:1 on the light ground, seven on the
// dark, and NONE fail on both. The palette spans the range properly; the
// grounds do not.
//
// The palette does not move to satisfy this. It is anchored to published
// emotion→colour associations and re-tuning a hex to pass a ratio would
// break the evidence the whole system rests on. The boundary moves instead:
// amendment §7.7 puts a hairline on every swatch, solved against the ground,
// and between every poster band. Universal rather than conditional — a rule
// that applies to eight of twenty is a rule someone forgets.
//
// These live here so the test suite can assert them. Editing a hex should
// tell you which ground you just broke.

const lin = (v) => { const c = v / 255; return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4; };

export function luminance(hex) {
  const m = /^#?([0-9a-f]{6})$/i.exec(String(hex || ''));
  if (!m) return null;
  const n = parseInt(m[1], 16);
  const [r, g, b] = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map(lin);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

export function contrast(a, b) {
  const [x, y] = [luminance(a), luminance(b)];
  if (x == null || y == null) return null;
  const [hi, lo] = x >= y ? [x, y] : [y, x];
  return (hi + 0.05) / (lo + 0.05);
}

/** The three grounds a swatch is ever drawn on. */
export const GROUNDS = Object.freeze({
  light:  '#F4F1EA',   // --ground, light
  dark:   '#191714',   // --ground, dark
  plinth: '#0E0D0F'    // the poster
});

/**
 * The ink a swatch can carry if type is ever set ON it.
 *
 * Not used by the swatch itself — the emotion word is set beside the swatch,
 * on the page ground, never over the colour — but the poster plinth and the
 * hatch label both need to know, and guessing per colour is how one of them
 * ends up at 2:1.
 */
export const inkOn = (hex) =>
  (contrast(hex, '#FFFFFF') >= contrast(hex, '#000000') ? '#FFFFFF' : '#000000');
